## Training a Makov Chain (Based on weather types)
- Implementing a transioin prob matrix from scratch using the weather col as the state apace and calulation each transision prob from that.

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('seattle.csv',)

# Cleaning the data 

# Removing empty cells as this is weather data
data = data.dropna()

# Cleaning  wrong date formats  
data['date'] = pd.to_datetime(data['date'],format= 'mixed')


In [24]:
# Trying to find the differnt possible states and define the statespace

types = set(data['weather'])
print(types)

{'sun', 'rain', 'fog', 'snow', 'drizzle'}


In [25]:
Weather = data['weather'] #<- The State Space is as follows {'snow', 'rain', 'drizzle', 'fog', 'sun'}
types = set(data['weather']) 

# Creating a func to make the intial transition  matrix with null values.
def CreateTransMatrix(df):
    dim = len(set(data['weather']))
    TransMatrix = np.zeros((dim,dim), dtype=float)
    return TransMatrix


# Building a function to get the probability oof each entry in the transtion prob. matrix 
def GetCellProb(df,State_1,State_2):
    # State 1 is the state x_t and State two is x_t+1 > Through the markov property
    # Plan: Go through the entire array(Temp) then if at i its state_1 and at i+1 its state_2 then add to a counter 
    Counter_trans = 0  # <- Number of desierd trans.
    Counter = 0 # <- Number of total trans.  
    for i in range(len(df)-1):
        if df[i] == State_1:
            if df[i+1] == State_2:
                Counter_trans += 1
                Counter += 1
            else:
                Counter += 1

    return (Counter_trans/Counter) if Counter > 0 else 0 #<- incase there are no trans.


# Test 
# print(GetCellProb(Weather,'snow','rain'))
# print(CreateTransMatrix(Weather))
# From the test i get the probalility from doing from snow to rain given the data that the model is provided with and to what the result od CreateTransMatrix is 

def GetTransitionProb(array):
    
    types = sorted(set(array))
    Matrix = CreateTransMatrix(array)

    for i in range(len(types)):
        for n in range(len(types)):
            Matrix[i,n] = GetCellProb(array,types[i],types[n])
    return Matrix

# Test
print(GetTransitionProb(Weather))


[[0.30188679 0.05660377 0.35849057 0.         0.28301887]
 [0.00990099 0.27722772 0.31683168 0.         0.3960396 ]
 [0.02808112 0.05616225 0.67394696 0.01716069 0.22464899]
 [0.03846154 0.         0.38461538 0.38461538 0.19230769]
 [0.02503912 0.05320814 0.23161189 0.00782473 0.68231612]]


### Dveloping simulation function from first principles 

In [32]:
# Initial distributio , selected arbitarily 
InitialDistribution = [0,0,1,0,0] #<- The state at the start is drizzel

CurrentState = 2

types = ['snow', 'rain', 'drizzle', 'fog', 'sun']

TransistionMatrix = GetTransitionProb(Weather)



# Creating a function that uses the forcast probability vector 

def ReturnNextState(TransistionMatrix,InitialDistribution,StateSpace):
    
    Probs = TransistionMatrix[InitialDistribution]

    NextState = np.random.choice(StateSpace,p=Probs)

    
    return NextState

print(ReturnNextState(TransistionMatrix,CurrentState,types))

rain
